[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
fs_permissions = [{access='read',path='.'}]

[rpc_endpoints]
mainnet = "https://eth-mainnet.g.alchemy.com/v2/RcrY_u7U77IxbQC1qOBqgbu-UDiGamwH"


# See more config options https://github.com/foundry-rs/foundry/tree/master/config